<?php
/**
 * Created by PhpStorm.
 * User: Andreea
 * Date: 20-Nov-18
 * Time: 10:26
 */

$routes = [
    '/' => ['controller' => 'RestaurantController',
            'action' => 'showAll',
            'guard' => 'Authenticated'],
    '/auth/login' => ['controller' => 'AuthController',
                    'action' => 'loginGET'],
    '/auth/login-action' => ['controller' => 'AuthController',
        'action' => 'loginPOST'],
    '/auth/register' => ['controller' => 'AuthController',
        'action' => 'registerGET'],
    '/auth/register-action' => ['controller' => 'AuthController',
        'action' => 'registerPOST'],
    '/auth/logout' => ['controller' => 'AuthController',
        'action' => 'logOutPost'],
    '/foods/show' => ['controller' => 'FoodController',
        'action' => 'showAll',
        'guard' => 'Authenticated'],
    '/foods/show-by-rest/{id}' =>['controller' => 'FoodController',
        'action' => 'showByRestauntName'],
    '/foods/show-food/{id}' => ['controller' => 'FoodController',
        'action' => 'show',
        'guard' => 'Authenticated'],
    '/user/edit' => ['controller' => 'UserController',
        'action' => 'updateGET',
        'guard' => 'Authenticated'],
    '/user/update-action' => ['controller' => 'UserController',
        'action' => 'updatePOST',
        'guard' => 'Authenticated'],
     '/error/notFound' => ['controller' => 'ErrorController',
         'action' => 'notFound'],
    '/error/unauthorized' => ['controller' => 'ErrorController',
        'action' => 'unauthorized'],
    '/user/show' => ['controller' => 'UserController',
        'action' => 'showAll',
        'guard' => 'Authenticated'],
    '/user/delete/{id}' => ['controller' => 'UserController',
        'action' => 'delete',
        'guard' => 'Authenticated'],
    '/food/delete/{id}' => ['controller' => 'FoodController',
        'action' => 'delete',
        'guard' => 'Authenticated'],
    '/restaurant/delete/{id}' => ['controller' => 'RestaurantController',
        'action' => 'delete',
        'guard' => 'Authenticated'],
    '/food/insert' => ['controller' => 'FoodController',
        'action' => 'insert',
        'guard' => 'Authenticated'],
    '/food/showAdmin' => ['controller' => 'FoodController',
        'action' => 'showAdmin',
        'guard' => 'Authenticated'],
    '/food/edit/{id}' => ['controller' => 'FoodController',
        'action' => 'updateGET',
        'guard' => 'Authenticated'],
    '/food/update-action' => ['controller' => 'FoodController',
        'action' => 'updatePOST',
        'guard' => 'Authenticated'],
    '/restaurant/insert' => ['controller' => 'RestaurantController',
        'action' => 'insert',
        'guard' => 'Authenticated'],
    '/restaurant/showAdmin' => ['controller' => 'RestaurantController',
        'action' => 'showAdmin',
        'guard' => 'Authenticated'],
    '/restaurant/edit/{id}' => ['controller' => 'RestaurantController',
        'action' => 'updateGET',
        'guard' => 'Authenticated'],
    '/restaurant/update-action' => ['controller' => 'RestaurantController',
        'action' => 'updatePOST',
        'guard' => 'Authenticated'],
];
